const fs = require("fs");
const path = require("path");
const assert = require("assert");

const root = __dirname;
const page = fs.readFileSync(path.join(root, "可视化", "板块轮动", "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "可视化", "板块轮动", "sector_rotation.css"), "utf8");
const js = fs.readFileSync(path.join(root, "可视化", "板块轮动", "sector_rotation.js"), "utf8");
const nav = fs.readFileSync(path.join(root, "可视化", "shared", "edge_float_nav.js"), "utf8");
const webStart = fs.readFileSync(path.join(root, "可视化", "start_web_server.bat"), "utf8");

assert.match(page, /<meta charset="UTF-8">/);
assert.match(page, /<title>板块轮动<\/title>/);
assert.match(page, /data-prefix="881"/);
assert.match(page, /data-prefix="882"/);
assert.match(page, /data-prefix="885"/);
assert.match(page, /data-prefix="886"/);
assert.match(page, /<span>粗行业<\/span>/);
assert.match(page, /<span>地域<\/span>/);
assert.match(page, /<span>早期细分概念<\/span>/);
assert.match(page, /<span>后期细分概念<\/span>/);
assert.match(page, /data-range="20d"/);
assert.match(page, /data-range="60d"/);
assert.match(page, /data-range="ytd"/);
assert.match(page, /id="custom-range-days"/);
assert.match(page, /id="custom-range-apply"/);
assert.doesNotMatch(page, />自定义<\/label>/);
assert.match(page, /data-sort="asc"/);
assert.match(page, /data-sort="desc"/);
assert.match(page, />收益率降低<\/button>/);
assert.match(page, />收益率提高<\/button>/);
assert.match(page, /id="sector-grid"/);
assert.match(page, /window\.PAGE_VIEW\s*=\s*"sector-rotation"/);
assert.match(css, /\.sector-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(3/);
assert.match(js, /\/api\/market\/index-codes/);
assert.match(js, /\/api\/market\/index\/bars/);
assert.match(js, /\/api\/market\/index\/returns/);
assert.match(js, /\/api\/market\/sector-constituents/);
assert.match(js, /dblclick/);
assert.match(page, /id="constituent-dialog"/);
assert.match(css, /\.constituent-list/);
assert.match(css, /\.constituent-sparkline/);
assert.match(js, /drawMiniCloseLine/);
assert.match(js, /closes_20d/);
assert.match(js, /20天曲线/);
assert.match(js, /constituent-return/);
assert.match(js, /toFixed\(2\)/);
assert.match(css, /\.constituent-return\.positive/);
assert.match(js, /IntersectionObserver/);
assert.match(js, /pinyin_initials/);
assert.match(js, /兼容未重启的旧 API/);
assert.match(js, /\/api\/market\/sector-memberships/);
assert.match(js, /getBoundingClientRect/);
assert.match(js, /addEventListener\("scroll"/);
assert.match(js, /MAX_CONCURRENT_REQUESTS\s*=\s*4/);
assert.match(js, /LightweightCharts\.CandlestickSeries/);
assert.match(js, /upColor:\s*"#ef5350"/);
assert.match(js, /downColor:\s*"#26a69a"/);
assert.match(js, /selectOhlcBars/);
assert.match(js, /state\.range\s*=\s*"custom"/);
assert.match(js, /customDays/);
assert.match(js, /1 到 2000/);
assert.match(js, /requestedLimit/);
assert.match(js, /sortCardsByReturn/);
assert.match(js, /state\.sortOrder/);
assert.match(js, /loadReturnsAndSort/);
assert.match(js, /sortActive/);
assert.match(js, /正在计算 .* 个板块的收益率/);
assert.doesNotMatch(js, /enqueueAllCardsForSorting/);
assert.doesNotMatch(js, /sortDataIsPending/);
assert.doesNotMatch(js, /sortRequested/);
assert.match(js, /isStockCodeQuery/);
assert.match(js, /stockSectorCodes/);
assert.match(js, /\/api\/market\/codes\/search/);
assert.match(js, /findStockCandidates/);
assert.match(js, /loadStockMemberships/);
assert.match(js, /renderSearchCandidates/);
assert.match(js, /findSectorCandidates/);
assert.match(js, /selectSectorCandidate/);
assert.match(js, /limit:\s*"8"/);
assert.match(js, /ArrowDown/);
assert.match(js, /ArrowUp/);
assert.match(js, /setActiveSearchOption/);
assert.match(js, /right\.returnRate - left\.returnRate/);
assert.match(page, /id="sector-search-suggestions"/);
assert.match(css, /\.sector-search-suggestions/);
assert.match(js, /candidate\.type === "sector"/);
assert.match(js, /searchRequestId/);
assert.match(page, /股票名称、首字母、代码或板块/);
assert.match(css, /\.control-band\.is-collapsed/);
assert.match(js, /bindAutoCollapseControls/);
assert.match(js, /delta\s*>\s*8/);
assert.match(js, /delta\s*<\s*-6/);
assert.match(js, /\/api\/market\/index\/returns\?[\s\S]*sortCardsByReturn\(\)/);
assert.doesNotMatch(js, /performance\.querySelector\("strong"\)\.textContent[\s\S]{0,180}sortCardsByReturn\(\)/);
assert.match(css, /--bg:\s*#131722/);
assert.match(css, /--surface:\s*#1e222d/);
assert.match(nav, /sector-rotation/);
assert.match(webStart, /板块轮动\/index\.html/);

console.log("板块轮动页面契约通过");
