const fs = require("fs");
const path = require("path");
const assert = require("assert");

const root = __dirname;
const pagePath = path.join(root, "可视化", "模型有效性", "index.html");
const navPath = path.join(root, "可视化", "shared", "edge_float_nav.js");
const livePagePath = path.join(root, "可视化", "实盘面", "index.html");
const liveCssPath = path.join(root, "可视化", "实盘面", "live_board.css");
const webStartPath = path.join(root, "可视化", "start_web_server.bat");
const rootWrapperPath = path.join(root, "可视化", "模型有效性.html");
const page = fs.readFileSync(pagePath, "utf8");
const nav = fs.readFileSync(navPath, "utf8");
const livePage = fs.readFileSync(livePagePath, "utf8");
const liveCss = fs.readFileSync(liveCssPath, "utf8");
const webStart = fs.readFileSync(webStartPath, "utf8");
const rootWrapper = fs.readFileSync(rootWrapperPath, "utf8");
const pageCss = fs.readFileSync(path.join(root, "可视化", "模型有效性", "model_validity.css"), "utf8");
const pageJs = fs.readFileSync(path.join(root, "可视化", "模型有效性", "model_validity.js"), "utf8");

assert.match(page, /<title>个股风格模型有效性<\/title>/);
assert.match(page, /window\.PAGE_VIEW\s*=\s*["']model-validity["']/);
assert.doesNotMatch(pageJs, /buildDemoSeries/);
assert.doesNotMatch(page, /data-chart-index=/);
assert.match(page, /id="style-summary-rankings"/);
assert.match(page, /id="style-chart-grid"/);
assert.doesNotMatch(page, /id="style-monitor-update"/);
assert.match(page, /理论监控/);
assert.match(page, /data-range="20d"/);
assert.match(page, /data-range="60d"/);
assert.match(page, /data-range="ytd"/);
assert.doesNotMatch(page, /data-range="all"/);
assert.match(page, /id="style-range-start"/);
assert.match(page, /id="style-range-end"/);
assert.match(page, /id="style-range-lookback"/);
assert.match(page, /id="style-range-apply"/);
assert.ok(page.indexOf('id="style-range-end"') < page.indexOf('id="style-range-lookback"'));
assert.ok(page.indexOf('id="style-range-lookback"') < page.indexOf('id="style-range-apply"'));
assert.match(page, /id="style-benchmark-code"/);
assert.match(page, /id="style-benchmark-apply"/);
assert.match(page, /id="style-benchmark-suggestions"/);
assert.ok(page.indexOf('id="style-range-apply"') < page.indexOf('id="style-benchmark-code"'));
assert.match(page, /id="style-detail-drawer"/);
assert.match(page, /data-detail-leg="high"/);
assert.match(page, /data-detail-leg="low"/);
assert.match(pageJs, /\/api\/style-monitor\/summary/);
assert.match(pageJs, /\/api\/style-monitor\/curves/);
assert.doesNotMatch(pageJs, /\/api\/style-monitor\/update/);
assert.match(pageJs, /createModelCard/);
assert.match(pageJs, /renderRankings/);
assert.match(pageJs, /renderPositions/);
assert.match(pageJs, /renderTrades/);
assert.doesNotMatch(pageJs, /startManualUpdate|pollUpdateJob|updateJobId/);
assert.match(page, /edge-float-hud/);
assert.match(page, /lightweight-charts\.standalone\.production\.js/);
assert.match(page, /href="\.\.\/实盘面\/index\.html"/);
assert.match(nav, /model-validity/);
assert.doesNotMatch(livePage, /live-model-link/);
assert.doesNotMatch(liveCss, /live-model-link/);
assert.match(webStart, /模型有效性\/index\.html/);
assert.match(rootWrapper, /模型有效性\/index\.html/);

assert.match(page, /model-validity-zoom-content/);
assert.match(page, /model-validity-zoom-controls/);
assert.match(page, /model-validity-zoom-decrease/);
assert.match(page, /model-validity-zoom-reset/);
assert.match(page, /model-validity-zoom-increase/);
assert.match(pageCss, /--model-validity-zoom/);
assert.match(pageCss, /body\.page-model-validity[\s\S]*?margin:\s*0/);
assert.match(pageCss, /\.model-validity-shell[\s\S]*?box-sizing:\s*border-box/);
assert.match(pageJs, /DEFAULT_ZOOM\s*=\s*1\.25/);
assert.match(pageJs, /localStorage/);
assert.match(pageJs, /model-validity-zoom-decrease/);
assert.match(pageJs, /model-validity-zoom-increase/);
assert.match(pageJs, /normalizeSeriesForRange/);
assert.match(pageJs, /normalizePayloadForRange/);
assert.match(pageJs, /subscribeVisibleTimeRangeChange/);
assert.match(pageJs, /setVisibleRange\(range\)/);
assert.match(pageJs, /syncingTimeRange/);
assert.match(pageJs, /value \/ base \* 100/);
assert.match(pageJs, /range === "custom"/);
assert.match(pageJs, /calculateLookbackStart/);
assert.match(pageJs, /style-range-lookback/);
assert.match(pageJs, /lookbackDays/);
assert.match(pageJs, /start_date/);
assert.match(pageJs, /end_date/);
assert.match(pageJs, /benchmark_code/);
assert.match(pageJs, /style-benchmark-code/);
assert.match(pageJs, /api\/market\/codes\/search/);
assert.match(pageJs, /SERIES_KEYS\s*=\s*\["high",\s*"low",\s*"relative",\s*"benchmark"\]/);
assert.match(pageJs, /高分/);
assert.match(pageJs, /低分/);
assert.match(pageJs, /相对/);
assert.doesNotMatch(pageJs, /high_net|low_net|relative_net|高分净|低分净|相对净/);
assert.doesNotMatch(page, /净曲线/);

console.log("模型有效性页面契约通过");
