#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""Validate stock_adj_daily outputs generated by the QMT adjustment script."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import polars as pl


SEGMENT_COLUMNS = ["htsc_code", "begin_date", "end_date", "xdy"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate QMT stock_adj_daily parquet layout")
    parser.add_argument("--base-dir", required=True, help="stock_adj_daily output directory")
    parser.add_argument("--raw-base-dir", default="", help="optional stock_adj_daily_raw directory")
    return parser.parse_args()


def fail(message: str) -> None:
    raise SystemExit(f"[FAIL] {message}")


def main() -> None:
    args = parse_args()
    base_dir = Path(args.base_dir)
    seg_path = base_dir / "adj_factor_segments.parquet"
    wide_root = base_dir / "wide_xdy"

    if not seg_path.is_file():
        fail(f"missing {seg_path}")

    seg = pl.read_parquet(str(seg_path))
    missing = [col for col in SEGMENT_COLUMNS if col not in seg.columns]
    if missing:
        fail(f"segment columns missing: {missing}; actual={seg.columns}")
    if seg.is_empty():
        fail("segment parquet is empty")

    seg = seg.select(SEGMENT_COLUMNS).with_columns(
        pl.col("htsc_code").cast(pl.Utf8).str.strip_chars().str.to_uppercase(),
        pl.col("begin_date").cast(pl.Date, strict=False),
        pl.col("end_date").cast(pl.Date, strict=False),
        pl.col("xdy").cast(pl.Float64, strict=False),
    )
    null_rows = seg.filter(pl.any_horizontal(pl.all().is_null())).height
    if null_rows:
        fail(f"segment contains null rows: {null_rows}")

    duplicate_keys = seg.group_by(["htsc_code", "begin_date"]).len().filter(pl.col("len") > 1).height
    if duplicate_keys:
        fail(f"duplicate segment keys: {duplicate_keys}")

    bad_dates = seg.filter(pl.col("begin_date") > pl.col("end_date")).height
    if bad_dates:
        fail(f"begin_date > end_date rows: {bad_dates}")

    bad_xdy = seg.filter(pl.col("xdy") <= 0).height
    if bad_xdy:
        fail(f"xdy <= 0 rows: {bad_xdy}")

    wide_files = sorted(wide_root.glob("year=*/month=*/merged.parquet"))
    if not wide_files:
        fail(f"missing wide_xdy merged parquet under {wide_root}")

    first_wide = pl.read_parquet(str(wide_files[0]), n_rows=1)
    if "htsc_code" not in first_wide.columns:
        fail(f"wide_xdy missing htsc_code column: {wide_files[0]}")

    raw_summary = {}
    if args.raw_base_dir:
        raw_base = Path(args.raw_base_dir)
        raw_files = sorted(raw_base.glob("year=*/month=*/merged.parquet"))
        raw_summary = {"raw_merged_files": len(raw_files)}
        if not raw_files:
            fail(f"missing raw merged parquet under {raw_base}")

    summary = {
        "base_dir": str(base_dir),
        "segment_rows": seg.height,
        "segment_codes": seg.select(pl.col("htsc_code").n_unique()).item(),
        "begin_min": str(seg.select(pl.col("begin_date").min()).item()),
        "begin_max": str(seg.select(pl.col("begin_date").max()).item()),
        "end_max": str(seg.select(pl.col("end_date").max()).item()),
        "wide_merged_files": len(wide_files),
        **raw_summary,
    }
    print("[OK] QMT adj output validation passed")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
