(function () {
    const API_BASE = resolveApiBaseUrl();
    const PERIODS = [1, 3, 5, 10, 20, 60];
    const state = { factors: [], groups: [], selectedFactor: "", lastResult: null, records: [], stockPools: [] };
    const el = {
        clock: document.getElementById("page-clock"), factorSearch: document.getElementById("factor-search"),
        factorList: document.getElementById("factor-list"), dropZone: document.getElementById("factor-drop-zone"),
        priceAdjustModes: Array.from(document.querySelectorAll('input[name="price-adjust-mode"]')),
        selectedFactor: document.getElementById("selected-factor"), startDate: document.getElementById("start-date"),
        endDate: document.getElementById("end-date"), stockPool: document.getElementById("stock-pool"),
        stockSummary: document.getElementById("stock-summary"),
        rollingWindow: document.getElementById("rolling-window"), groupCount: document.getElementById("group-count"),
        runBtn: document.getElementById("run-btn"),
        status: document.getElementById("status-line"), qualityCards: document.getElementById("quality-cards"),
        qualityChart: document.getElementById("quality-chart"), icSummary: document.getElementById("ic-summary"),
        cumIcChart: document.getElementById("cum-ic-chart"), rollingIcChart: document.getElementById("rolling-ic-chart"),
        groupChart: document.getElementById("group-chart"), groupTable: document.getElementById("group-table"),
        eventSummary: document.getElementById("event-summary"), eventChart: document.getElementById("event-chart"),
        recordsList: document.getElementById("records-list"), scrollDeck: document.getElementById("scroll-deck"),
    };
    const sectionLinks = Array.from(document.querySelectorAll(".section-jump-link"));
    const t = {
        unselected: "\u672a\u9009\u62e9", waiting: "\u7b49\u5f85\u9009\u62e9\u56e0\u5b50", selected: "\u5df2\u9009\u62e9",
        ungrouped: "\u672a\u5206\u7c7b", noMatch: "\u6ca1\u6709\u5339\u914d\u56e0\u5b50", allFactors: "\u5168\u90e8\u56e0\u5b50",
        chooseFirst: "\u8bf7\u5148\u9009\u62e9\u56e0\u5b50", running: "\u6b63\u5728\u8ba1\u7b97\uff0c\u65f6\u95f4\u533a\u95f4\u8d8a\u957f\u4f1a\u8d8a\u6162...",
        submitted: "\u4efb\u52a1\u5df2\u63d0\u4ea4", elapsed: "\u5df2\u7528\u65f6", seconds: "\u79d2",
        done: "\u5b8c\u6210", calcFailed: "\u8ba1\u7b97\u5931\u8d25", saveRunning: "\u6b63\u5728\u4fdd\u5b58\u6210\u679c...",
        saveDone: "\u6210\u679c\u5df2\u4fdd\u5b58", saveFailed: "\u4fdd\u5b58\u5931\u8d25", restored: "\u5df2\u6062\u590d\u6210\u679c",
        deleted: "\u8bb0\u5f55\u5df2\u5220\u9664", deleteFailed: "\u5220\u9664\u5931\u8d25", noRecords: "\u6682\u65e0\u4fdd\u5b58\u7684\u56e0\u5b50\u6210\u679c",
        view: "\u67e5\u770b", del: "\u5220\u9664", initFailed: "\u521d\u59cb\u5316\u5931\u8d25",
        avgValid: "\u5e73\u5747\u6709\u6548\u80a1\u7968\u6570", avgCoverage: "\u5e73\u5747\u8986\u76d6\u7387", avgAbnormal: "\u5e73\u5747\u5f02\u5e38\u503c\u6bd4\u4f8b", emptyDates: "\u5168\u7a7a\u65e5\u671f\u6570",
        validCount: "\u6709\u6548\u80a1\u7968\u6570", coverage: "\u8986\u76d6\u7387", dataQuality: "\u6570\u636e\u8d28\u91cf",
        period: "\u5468\u671f", icMean: "IC\u5747\u503c", rankIcMean: "RankIC\u5747\u503c", winRate: "\u80dc\u7387", sampleDays: "\u6837\u672c\u65e5",
        cumIc: "\u7d2f\u8ba1 IC", rollingIc: "\u6eda\u52a8 IC", groupCum: "\u5206\u7ec4\u7d2f\u8ba1\u6536\u76ca", group: "\u7ec4", samples: "\u6837\u672c\u6570", avgReturn: "\u5e73\u5747\u6536\u76ca",
        eventCount: "\u4e8b\u4ef6\u6570", medianReturn: "\u4e2d\u4f4d\u6570\u6536\u76ca", rollingEvent: "\u6eda\u52a8\u4e8b\u4ef6\u6536\u76ca",
        stockPoolsLoaded: "\u5df2\u8f7d\u5165\u80a1\u7968\u6c60\u6587\u4ef6", noStockPools: "\u672a\u627e\u5230\u80a1\u7968\u6c60\u6587\u4ef6",
    };
    function resolveApiBaseUrl() { try { if (location.protocol === "http:" || location.protocol === "https:") return `http://${location.hostname}:8000`; } catch (_) {} return "http://127.0.0.1:8000"; }
    function setStatus(message, isError) { el.status.textContent = message || ""; el.status.classList.toggle("error", Boolean(isError)); }
    function todayStr() { return new Date().toISOString().slice(0, 10); }
    function addYears(date, years) { const d = new Date(date); d.setFullYear(d.getFullYear() + years); return d.toISOString().slice(0, 10); }
    function initDates() { const end = todayStr(); el.endDate.value = end; el.startDate.value = addYears(end, -3); }
    async function apiJson(path, options) { const res = await fetch(`${API_BASE}${path}`, options || {}); const payload = await res.json().catch(() => ({})); if (!res.ok) throw new Error(payload?.error?.message || `HTTP ${res.status}`); return payload; }
    function escapeHtml(value) { return String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
    function formatPct(value) { const n = Number(value); return Number.isFinite(n) ? `${(n * 100).toFixed(2)}%` : "--"; }
    function formatNum(value, digits) { const n = Number(value); return Number.isFinite(n) ? n.toFixed(digits == null ? 4 : digits) : "--"; }
    function table(headers, rows) { return `<table><thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((v) => `<td>${escapeHtml(v)}</td>`).join("")}</tr>`).join("")}</tbody></table>`; }
    function getPriceAdjustMode() { const checked = el.priceAdjustModes.find((node) => node.checked); return checked ? checked.value : "none"; }
    function setPriceAdjustMode(mode) { const value = mode === "backward_ratio" ? "backward_ratio" : "none"; el.priceAdjustModes.forEach((node) => { node.checked = node.value === value; node.closest(".adjust-mode-option")?.classList.toggle("active", node.checked); }); }
    function selectFactor(name) { state.selectedFactor = String(name || "").trim(); el.selectedFactor.textContent = state.selectedFactor || t.unselected; document.querySelectorAll(".factor-item.active").forEach((node) => node.classList.remove("active")); if (state.selectedFactor) document.querySelectorAll(`.factor-item[data-factor="${CSS.escape(state.selectedFactor)}"]`).forEach((node) => node.classList.add("active")); setStatus(state.selectedFactor ? `${t.selected} ${state.selectedFactor}` : t.waiting); }
    function renderFactors() { const q = String(el.factorSearch.value || "").trim().toLowerCase(); const html = state.groups.map((group) => { const children = Array.isArray(group.children) ? group.children : []; const matched = children.filter((name) => !q || `${group.group_name || ""} ${name}`.toLowerCase().includes(q)); if (!matched.length) return ""; return `<div class="factor-group"><div class="factor-group-title">${escapeHtml(group.group_name || group.group_id || t.ungrouped)}</div>${matched.map((name) => `<div class="factor-item${name === state.selectedFactor ? " active" : ""}" data-factor="${escapeHtml(name)}"><span>${escapeHtml(name)}</span></div>`).join("")}</div>`; }).join(""); el.factorList.innerHTML = html || `<div class="status-line">${t.noMatch}</div>`; }
    async function loadFactors() { const payload = await apiJson("/api/factor-validation/factors"); state.factors = Array.isArray(payload.factors) ? payload.factors : []; state.groups = Array.isArray(payload.groups) ? payload.groups : [{ group_id: "all", group_name: t.allFactors, children: state.factors }]; renderFactors(); }
    function renderStockPools() { if (!state.stockPools.length) { el.stockPool.innerHTML = `<option value="">${escapeHtml(t.noStockPools)}</option>`; el.stockSummary.textContent = t.noStockPools; return; } el.stockPool.innerHTML = state.stockPools.map((item) => `<option value="${escapeHtml(item.name)}"${item.is_default ? " selected" : ""}>${escapeHtml(item.label || item.name)}</option>`).join(""); updateStockSummary(); }
    function updateStockSummary() { const selected = state.stockPools.find((item) => item.name === el.stockPool.value); el.stockSummary.textContent = selected ? `${selected.name}` : t.noStockPools; }
    async function loadStockPools() { const payload = await apiJson("/api/factor-validation/stock-pools"); state.stockPools = Array.isArray(payload.items) ? payload.items : []; renderStockPools(); if (state.stockPools.length) el.stockSummary.textContent = `${t.stockPoolsLoaded} ${state.stockPools.length}`; }
    async function loadRecords() { const payload = await apiJson("/api/factor-validation/records"); state.records = Array.isArray(payload.items) ? payload.items : []; renderRecords(); }
    function requestPayload() { return { factor: state.selectedFactor, stock_pool: el.stockPool.value || "ALL_A", stock_pool_file: el.stockPool.value, start_date: el.startDate.value, end_date: el.endDate.value, periods: PERIODS, rolling_window: Number(el.rollingWindow.value || 60), group_count: Number(el.groupCount.value || 5), price_adjust_mode: getPriceAdjustMode() }; }
    function sleep(ms) { return new Promise((resolve) => window.setTimeout(resolve, ms)); }
    function jobStatusMessage(job) { const parts = [job.stage || job.status || t.running]; if (job.message) parts.push(job.message); if (Number.isFinite(Number(job.elapsed_seconds))) parts.push(`${t.elapsed} ${Number(job.elapsed_seconds).toFixed(1)} ${t.seconds}`); if (job.job_id) parts.push(`ID ${job.job_id}`); return parts.join(" | "); }
    async function waitForValidationJob(jobId) { let job = null; while (jobId) { job = await apiJson(`/api/factor-validation/jobs?id=${encodeURIComponent(jobId)}`); setStatus(jobStatusMessage(job), job.status === "failed"); if (job.status === "done") return job.result; if (job.status === "failed") throw new Error(job.error?.message || job.message || t.calcFailed); await sleep(1500); } throw new Error(t.calcFailed); }
    async function runValidation() { if (!state.selectedFactor) { setStatus(t.chooseFirst, true); return; } setStatus(t.running); el.runBtn.disabled = true; try { const job = await apiJson("/api/factor-validation/run", { method: "POST", headers: { "Content-Type": "application/json; charset=utf-8" }, body: JSON.stringify(requestPayload()) }); setStatus(`${t.submitted}: ${jobStatusMessage(job)}`); const result = job.job_id ? await waitForValidationJob(job.job_id) : job; state.lastResult = result; renderResult(result); await saveRecord(); } catch (err) { setStatus(err instanceof Error ? err.message : t.calcFailed, true); } finally { el.runBtn.disabled = false; } }
    function plotLayout(title) { return { title: { text: title, font: { color: "#e6edf3", size: 14 } }, paper_bgcolor: "#151b23", plot_bgcolor: "#151b23", font: { color: "#c9d1d9" }, margin: { l: 48, r: 18, t: 46, b: 40 }, xaxis: { gridcolor: "#2f3a48" }, yaxis: { gridcolor: "#2f3a48" }, legend: { orientation: "h" } }; }
    function plotConfig() { return { responsive: true, displaylogo: false }; }
    function renderQuality(result) { const q = result.quality || {}; el.qualityCards.innerHTML = [[t.avgValid, formatNum(q.avg_valid_stock_count, 0)], [t.avgCoverage, formatPct(q.avg_coverage)], [t.avgAbnormal, formatPct(q.avg_abnormal_ratio)], [t.emptyDates, Array.isArray(q.empty_dates) ? q.empty_dates.length : 0]].map(([label, value]) => `<div class="metric-card"><div class="metric-label">${escapeHtml(label)}</div><div class="metric-value">${escapeHtml(value)}</div></div>`).join(""); const daily = Array.isArray(q.daily) ? q.daily : []; Plotly.newPlot(el.qualityChart, [{ x: daily.map((d) => d.date), y: daily.map((d) => d.valid_stock_count), name: t.validCount, type: "scatter", mode: "lines" }, { x: daily.map((d) => d.date), y: daily.map((d) => d.coverage), name: t.coverage, type: "scatter", mode: "lines", yaxis: "y2" }], { ...plotLayout(t.dataQuality), yaxis2: { overlaying: "y", side: "right", tickformat: ".0%" } }, plotConfig()); }
    function renderIc(result) { const summary = Array.isArray(result.ic_summary) ? result.ic_summary : []; el.icSummary.innerHTML = table([t.period, t.icMean, t.rankIcMean, "ICIR", t.winRate, t.sampleDays], summary.map((row) => [`${row.period}D`, formatNum(row.ic_mean), formatNum(row.rank_ic_mean), formatNum(row.icir), formatPct(row.win_rate), row.count || 0])); const traces = []; for (const period of PERIODS) { const rows = result.ic_series && result.ic_series[String(period)] || []; traces.push({ x: rows.map((d) => d.date), y: rows.map((d) => d.cum_ic), name: `${period}D`, type: "scatter", mode: "lines" }); } Plotly.newPlot(el.cumIcChart, traces, plotLayout(t.cumIc), plotConfig()); }
    function renderRolling(result) { const traces = []; for (const period of PERIODS) { const rows = result.rolling_ic && result.rolling_ic[String(period)] || []; traces.push({ x: rows.map((d) => d.date), y: rows.map((d) => d.rolling_ic), name: `${period}D ${t.rollingIc}`, type: "scatter", mode: "lines" }); } Plotly.newPlot(el.rollingIcChart, traces, plotLayout(t.rollingIc), plotConfig()); }
    function renderGroups(result) { const period = "20"; const payload = result.group_returns && (result.group_returns[period] || result.group_returns["1"]); const groups = payload && Array.isArray(payload.groups) ? payload.groups : []; const traces = groups.map((group) => ({ x: (group.series || []).map((d) => d.date), y: (group.series || []).map((d) => d.cum_return), name: `G${group.group}`, type: "scatter", mode: "lines" })); Plotly.newPlot(el.groupChart, traces, plotLayout(`${t.groupCum} ${payload === result.group_returns?.[period] ? "20D" : "1D"}`), plotConfig()); el.groupTable.innerHTML = table([t.group, t.samples, t.avgReturn], groups.map((g) => [`G${g.group}`, g.count || 0, formatPct(g.mean_return)])); }
    function renderEvents(result) { const study = result.event_study || {}; const summary = Array.isArray(study.summary) ? study.summary : []; el.eventSummary.innerHTML = table([t.period, t.eventCount, t.avgReturn, t.medianReturn, t.winRate], summary.map((row) => [`${row.period}D`, row.event_count || 0, formatPct(row.mean_return), formatPct(row.median_return), formatPct(row.win_rate)])); const traces = []; for (const period of PERIODS) { const rows = study.rolling && study.rolling[String(period)] || []; traces.push({ x: rows.map((d) => d.date), y: rows.map((d) => d.rolling_mean_return), name: `${period}D`, type: "scatter", mode: "lines" }); } Plotly.newPlot(el.eventChart, traces, plotLayout(`${t.rollingEvent} | ${study.mode || ""}`), plotConfig()); }
    function renderResult(result) { renderQuality(result); renderIc(result); renderRolling(result); renderGroups(result); renderEvents(result); }
    function setActiveSection(targetId) { sectionLinks.forEach((link) => link.classList.toggle("active", link.dataset.target === targetId)); }
    function syncActiveSection() { if (!sectionLinks.length || !el.scrollDeck) return; const deckRect = el.scrollDeck.getBoundingClientRect(); let bestId = sectionLinks[0].dataset.target || ""; let bestDistance = Infinity; sectionLinks.forEach((link) => { const panel = document.getElementById(link.dataset.target || ""); if (!panel) return; const distance = Math.abs(panel.getBoundingClientRect().top - deckRect.top); if (distance < bestDistance) { bestDistance = distance; bestId = panel.id; } }); setActiveSection(bestId); }
    function bindSectionNav() { if (!sectionLinks.length || !el.scrollDeck) return; sectionLinks.forEach((link) => { link.addEventListener("click", (event) => { event.preventDefault(); const panel = document.getElementById(link.dataset.target || ""); if (!panel) return; panel.scrollIntoView({ behavior: "smooth", block: "start" }); history.replaceState(null, "", `#${panel.id}`); setActiveSection(panel.id); }); }); el.scrollDeck.addEventListener("scroll", () => window.requestAnimationFrame(syncActiveSection), { passive: true }); window.addEventListener("resize", syncActiveSection); }
    function buildRecordPayload() { const result = state.lastResult || {}; const meta = result.meta || {}; return { factor: meta.factor || state.selectedFactor, stock_pool: meta.stock_pool || el.stockPool.value, stock_pool_file: meta.stock_pool_file || el.stockPool.value, start_date: meta.start_date || el.startDate.value, end_date: meta.end_date || el.endDate.value, periods: meta.periods || PERIODS, rolling_window: meta.rolling_window || Number(el.rollingWindow.value || 60), group_count: meta.group_count || Number(el.groupCount.value || 5), price_adjust_mode: meta.price_adjust_mode || getPriceAdjustMode(), quality: result.quality || {}, ic_summary: result.ic_summary || [], event_summary: result.event_study ? result.event_study.summary : [], chart_payload: { ic_series: result.ic_series || {}, rolling_ic: result.rolling_ic || {}, group_returns: result.group_returns || {}, event_study: result.event_study || {} } }; }
    async function saveRecord() { if (!state.lastResult) return; setStatus(t.saveRunning); try { await apiJson("/api/factor-validation/records", { method: "POST", headers: { "Content-Type": "application/json; charset=utf-8" }, body: JSON.stringify(buildRecordPayload()) }); await loadRecords(); setStatus(t.saveDone); } catch (err) { setStatus(err instanceof Error ? err.message : t.saveFailed, true); } }
    function restoreRecord(record) { state.selectedFactor = record.factor || ""; if (record.stock_pool_file) el.stockPool.value = record.stock_pool_file; updateStockSummary(); el.startDate.value = record.start_date || el.startDate.value; el.endDate.value = record.end_date || el.endDate.value; el.rollingWindow.value = record.rolling_window || 60; el.groupCount.value = record.group_count || 5; setPriceAdjustMode(record.price_adjust_mode || "none"); selectFactor(state.selectedFactor); const restored = { quality: record.quality || {}, ic_summary: record.ic_summary || [], event_study: record.chart_payload ? record.chart_payload.event_study : { summary: record.event_summary || [], rolling: {} }, ic_series: record.chart_payload ? record.chart_payload.ic_series : {}, rolling_ic: record.chart_payload ? record.chart_payload.rolling_ic : {}, group_returns: record.chart_payload ? record.chart_payload.group_returns : {}, meta: record }; state.lastResult = restored; renderResult(restored); setStatus(`${t.restored}: ${record.factor || ""}`); }
    async function deleteRecord(id) { if (!id) return; try { await apiJson(`/api/factor-validation/records?id=${encodeURIComponent(id)}`, { method: "DELETE" }); await loadRecords(); setStatus(t.deleted); } catch (err) { setStatus(err instanceof Error ? err.message : t.deleteFailed, true); } }
    function renderRecords() { if (!state.records.length) { el.recordsList.innerHTML = `<div class="status-line">${t.noRecords}</div>`; return; } el.recordsList.innerHTML = state.records.map((record) => `<div class="record-card" data-id="${escapeHtml(record.id)}"><div><div class="record-title">${escapeHtml(record.factor || "--")}</div><div class="record-meta">${escapeHtml(record.start_date || "")} ~ ${escapeHtml(record.end_date || "")} | ${escapeHtml(record.created_at || "")}</div></div><button class="small-btn restore-record" type="button">${t.view}</button><button class="small-btn delete-record" type="button">${t.del}</button></div>`).join(""); }
    function bindEvents() { el.factorSearch.addEventListener("input", renderFactors); el.factorList.addEventListener("click", (event) => { const item = event.target.closest(".factor-item"); if (item) selectFactor(item.dataset.factor || ""); }); el.stockPool.addEventListener("change", updateStockSummary); el.priceAdjustModes.forEach((node) => node.addEventListener("change", () => setPriceAdjustMode(getPriceAdjustMode()))); el.runBtn.addEventListener("click", runValidation); el.recordsList.addEventListener("click", (event) => { const card = event.target.closest(".record-card"); if (!card) return; const id = card.dataset.id || ""; const record = state.records.find((item) => item.id === id); if (event.target.closest(".restore-record") && record) restoreRecord(record); else if (event.target.closest(".delete-record")) void deleteRecord(id); }); }
    function tickClock() { if (el.clock) el.clock.textContent = `Time: ${new Date().toLocaleString("zh-CN", { hour12: false })}`; }
    async function boot() { initDates(); setPriceAdjustMode("none"); bindEvents(); bindSectionNav(); tickClock(); syncActiveSection(); setInterval(tickClock, 1000); try { await Promise.all([loadFactors(), loadStockPools(), loadRecords()]); setStatus(t.waiting); } catch (err) { setStatus(err instanceof Error ? err.message : t.initFailed, true); } }
    document.addEventListener("DOMContentLoaded", boot);
})();
